### PR TITLE
fixed stuff

### PR DESCRIPTION
**Pull request by AaaRandomPerson**
i cant lie, i have not tested whether this works or not. i'm pretty sure it does, theres no reason it shouldnt

anyways i fixed emojis and added variation on welcome message
also changed the way token is handled, idk if you want to change it back or not - it is what works for me

### CODE REVIEW

**Review by c0nD — CHANGES_REQUESTED** [review]
`if os.getcwd() == 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0':`

The bot currently runs on a linux server, so maybe check to make sure this could work on any environment.

**Comment by AaaRandomPerson** [comment]
> `if os.getcwd() == 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0':`

os.chdir(os.path.dirname(os.path.abspath(__file__)))

i think that would (probably) work

**Comment by c0nD** [comment]
> > `if os.getcwd() == 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0':`
> 
> os.chdir(os.path.dirname(os.path.abspath(**file**)))
> 
> i think that would (probably) work

Feel free to update the PR and recommit. Then I'll merge to main.

**Comment by AaaRandomPerson** [comment]
> Feel free to update the PR and recommit. Then I'll merge to main.

fixed i think 😎👍

**Comment by c0nD** [comment]
looks good to me

**Pull request merged**
